### ISSUE TITLE
CAP-0046 support — InvokeHostFunction operation

### ISSUE THREAD

**Issue by miguelnietoa** [kommitters/stellar_sdk#276]
ℹ️ This issue is an Epic

## Context
[CAP-0046](https://github.com/stellar/stellar-protocol/blob/master/core/cap-0046.md) specifies changes made to the Stellar Core XDR to support smart contracts.
CAP-0046 is already supported in the [stellar_base](https://github.com/kommitters/stellar_base) library (`v0.9.0`), so we must now provide the operation in the SDK to be built and sent to the Futurenet via Horizon.

## Objective
To add support for the invocation and deployment of Soroban smart contracts through the `InvokeHostFunction` operation.

## Checklist
- [ ] Invoke Contract Function
- [ ] Invoke Auth Contract Function
- [ ] Install Contract Code
- [ ] Create Contract

**Comment by miguelnietoa** [comment]
ℹ️ **Soroban Preview 7 support** added in `v0.12.0` 🎉
